# ===============================
# Service configuration
# ===============================
spring.application.name=${SPRING_APPLICATION_NAME:PRODUCT-SERVICE}
server.port=${SERVER_PORT:8081}

# ===============================
# Eureka client configuration
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

# ===============================
# Database configuration
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/productservicedb}
spring.datasource.username=${DB_USERNAME:productservice}
spring.datasource.password=${DB_PASSWORD:S2011nppd}

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=${FLYWAY_ENABLED:true}

# ===============================
# Product provider config
# ===============================
product.read.provider=${PRODUCT_PROVIDER:self}

# External API
fakestore.api.url=${FAKESTORE_API_URL:https://fakestoreapi.com/products}

# ===============================
# Redis configuration
# ===============================
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}

# Enable Spring Cache with Redis
spring.cache.type=${CACHE_TYPE:redis}

# ===============================
# Elasticsearch (disabled)
# ===============================
#spring.elasticsearch.uris=http://localhost:9200
